### ISSUE TITLE
Create a starter scaffold repo with our defaults

### ISSUE THREAD

**Issue by artntek** [DataONEorg/k8s-cluster#54]
Create a starter scaffold repo with our defaults, for use with `helm create -p` for new projects

https://helm.sh/docs/helm/helm_create/

**Comment by artntek** [comment]
Include `ingress` config for `defaultBackend` - [example from ADC values.yaml](https://github.nceas.ucsb.edu/NCEAS/k8s-cluster-config/blob/347c7f1212c5a110306a2f8956011ebf14fe46d1/prod_cluster/metacatarctic/values-prod-cluster-arctic.yaml#L104):

```yaml
ingress:
  defaultBackend:
    enabled: true
    service:
      name: wparctic-wordpress
      port:
        number: 80
```
and [here's where it gets inserted](https://github.com/NCEAS/metacat/blob/055790de3dc4dcb825c935e2815e758c9d1d7976/helm/templates/ingress.yaml#L47) into `metacat/helm/templates/ingress.yaml`
