### ISSUE TITLE
New GNIS Namespace, Volume Provision, and Ingress Ruleset

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/k8s-cluster#9]
To prep for deploying the GNIS-LD stack, we'll need a few things.

1. [x] A new namespace for the collection of pods. I think that `gnis` should be fine.
2. [x] A pv with 100GB of space
3. [ ] An ingress rule to expose the graphdb service to the NCEAS subnet
4. [ ] A new user account, 'gnis'
5. [x] A new GitHub repository holding the Kubernetes deployment files

I haven't created an official DataONE repo for the k8 configuration files yet; I've put them [here](https://github.com/ThomasThelen/gnis-stack/tree/master/gnis/templates) in the meantime.

**Comment by mbjones** [comment]
@ThomasThelen thanks. Please move the repo into the DataONEorg organization. The easiest way is to probably change ownership, although if you prefer, we can create an empty repo and sync what you have.

**Comment by ThomasThelen** [comment]
Definitely. I wanted vet the name (maybe `gnis-deployment` or `gnis-k8` - maybe we want to standardize k8 deployment repo names?) on the dev call today to avoid bugging anyone to go back and make repo level settings changes at a later time. I'm going to go ahead and fix the directory structure and aside from the name I think it should be good

**Comment by ThomasThelen** [comment]
@mbjones Given the call today how about creating a new repository called `gnis-deployment` on the `DataONEorg` organization? I dialed in the gitignore so I'll just copy the files over and get rid of the one on my account.

**Comment by ThomasThelen** [comment]
@gothub for the ingress route, would you like me to create an issue/PR in api-entrypoint? It should be exposed like

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: gnis-controller
  namespace: gnis
spec:
  host: api.test.dataone.org
  upstreams:
  - name: gnis-controller
    service: gnis-controller
    port: 7200
  subroutes:
  - path: /gnis
    action:
      pass: gnis-controller
```
